'use strict';
{
	let wordsArray=[];

	wordsArray.push("semester","undergraduate","vessel","grocery","postage","skyscraper","attic","nursery","academy","blunder","recipe","toil","vocabulary","affluence","coincidence","flu","chamber","slaughter","sermon","commodity","widow","bureau","ornament","token","stain");
	wordsArray.push("stationery","hedge","fur","nightmare","murmur","margin","disgust","trifle","rubbish","storage","scold","furnish","dye","yell","dwell","sustain","pronounce","grab","fetch","contradict","strip","recollect","squeeze","rear","undo");
	wordsArray.push("reproach","insert","utilize","rattle","yawn","bite","blink","cram","equip","incorporate","uncover","dump","conform","inhabit","slam","unfold","donate","devastate","peel","peep","isolate","summarize","misuse","tread","embody");
	wordsArray.push("customary","sophisticated","worthy","blank","prior","definite","messy","hospitable","simultaneous","apparent","ample","profound","routine","foul","gloomy","rotten","monotonous","trivial","numerous","concise","conspicuous","occasional","feminine","momentary","pregnant");

	wordsArray.push("statesman","minister","bribe","revolution","depression","statistics","hostage","merchandise","retail","anarchy","deposit","headquarters","communism","attachment","embassy","revenue","monopoly","harassment","apprehension","friction","diplomacy","questionnaire","fraction","ransom","variety");
	wordsArray.push("contribution","consumption","lump","assembly","behalf","budget","mayor","frequency","production","probability","garbage","premier","hatred","denial","Senate","invest","whisper","derive","evaluate","elect","calculate","discourage","assemble","scorn","lessen");
	wordsArray.push("signify","shed","categorize","ally","restrict","reign","plead","shrink","dispute","soar","advocate","accumulate","retreat","collide","reckon","retain","rebel","administer","coop","detach","foresee","collaborate","urge","evolve","resign");
	wordsArray.push("govern","qualify","restructure","specify","nominate","economical","elaborate","equivalent","drastic","notorious","patriotic","affluent","gross","relevant","substantial","crucial","bankrupt","intent","ecological","competent","commonplace","priceless","conservative","diplomatic","static");

	wordsArray.push("compliment","dignity","passion","bond","irony","nuisance","hardship","courtesy","hypocrisy","disgust","curiosity","melancholy","snob","torment","contempt","malice","harassment","dismay","consolation","salute","antipathy","tact","temptation","anguish","connection");
	wordsArray.push("apprehension","aspiration","wit","modesty","vanity","discourage","amaze","scare","embarrass","despise","bore","tease","ridicule","boast","yearn","bewilder","bully","weep","comprehend","compromise","flatter","scorn","mourn","inquire","mock");
	wordsArray.push("lament","forbear","grin","obsess","provoke","misunderstand","humimliate","chuckle","frustrate","resent","sympathize","exaggerrate","sob","terrify","chat","depress","dread","irritate","moan","mutter","amiable","diligent","stern","intimate","earnest");
	wordsArray.push("rational","timid","prudent","obstinate","talkative","eloquent","cunning","furious","greedy","indebted","dubious","vulgar","arrogant","resentful","reckless","skeptical","brutal","cordial","cynical","naive","arbitrary","eccentric","sober","restless","tolerant");
	
	wordsArray.push("conscience","orphan","metropolice","perspective","bias","propaganda","penalty","aristocracy","transaction","session","throng","standstill","oath","breakthrough","warrant","errand","innovation","fuss","legislation","controversy","council","pledge","predecessor","agenda","admission");
	wordsArray.push("guideline","clash","unemployment","vow","input","poll","publicity","publisher","recism","reception","renewal","representative","revolt","royalty","scholarship","sentiment","sociology","standpoint","tendency","theft","urge","impose","disclose","capture","execute");
	wordsArray.push("swear","restrict","exploit","acknowledge","cite","consent","oblige","confess","deprive","betray","ensure","negotiate","enforce","proclaim","foster","defy","restrain","banish","expel","summon","flee","confine","implement","revenge","detain");
	wordsArray.push("sue","kidnap","ascertain","convict","meditate","abandon","authorize","constitute","insure","regulate","bound","respectable","absurd","liable","juvenile","compulsory","deliberate","grave","judicial","rigid","invalid","legitimate","valid","conclusive","detached");
	
	wordsArray.push("frontier","wilderness","atlas","clue","summary","proverb","barrier","fate","triumph","famine","souvenir","excursion","timber","plot","queue","adversity","wreck","maxim","anecdote","axis","pedestrian","carriage","formula","tyrant","fable");
	wordsArray.push("strain","cradle","transition","archive","pillar","segregation","profile","offspring","navigation","expedition","tomb","doom","haven","barbarian","realm","narrative","memento","geography","landscape","race","dinosaur","canyon","chronicle","quest","usage");
	wordsArray.push("resort","peasant","pioneer","prefecture","twilight","board","suppress","undertake","tolerate","enclose","withdraw","split","cultivate","enlarge","flourish","embark","migrate","roam","prevail","repel","assault","originate","discriminate","divert","differ");
	wordsArray.push("dominate","mislead","stray","unlock","widen","cruise","depart","overthrow","navigate","stroll","global","primitive","historic","conventional","medieval","sole","infamous","fertile","hostile","armed","pathentic","widespread","imperial","cutomary","exotic");
	
	wordsArray.push("physician","organ","circulation","lump","removal","span","remedy","supplement","cough","certificate","nutrition","refuge","shelter","calamity","donation","prescription","specimen","plague","apparatus","might","consensus","skeleton","toxing","scar","agony");
	wordsArray.push("groan","oppression","lung","distress","fiber","bacteria","virus","surgery","therapy","precaution","prevention","provision","surgeon","thirst","tumor","exhaust","dispense","acquaint","refresh","swallow","lower","overwhelm","transmit","rotate","bind");
	wordsArray.push("inspect","extract","tremble","shiver","bleed","sniff","sneeze","gasp","penetrate","pant","frown","scatter","detect","inflict","plunge","torture","stoop","drain","pierce","subside","diagnose","prescribe","evacuate","reassure","choke");
	wordsArray.push("dip","revive","weaken","regain","rinse","weary","uneasy","dizzy","disable","exessive","pale","deadly","lean","bald","prompt","innate","dumb","insane","abrupt","immune","sanitary","credible","vulnerable","infectious","terminal");
	
	wordsArray.push("globe","cosmos","mineral","volcano","core","breeze","ape","biology","clay","particle","hemisphere","microscope","drought","radioactivity","bloom","prey","frost","ingredient","barometer","comet","astronomy","stem","botany","ecology","blast");
	wordsArray.push("heap","radius","evaporation","dimension","geometry","ray","weed","chemistry","carbon","anthropology","molecule","emission","galaxy","plow","preservation","radiation","rainfall","reptile","stalk","typhoon","roar","crack","extinguish","hatch","soak");
	wordsArray.push("conserve","refine","convert","emit","perish","peer","dissolve","dispose","distort","deduce","reap","sort","classify","generate","creep","drip","emerge","sow","sparkle","blaze","lick","overflow","revolve","sway","scan");
	wordsArray.push("awful","vertical","solar","extinct","damp","dreadful","ripe","tame","dim","secondary","inherent","singular","moderate","faint","innumerable","spectacular","transparent","fierce","serene","compound","atomic","genetic","dual","antarctic","ecological");
	
	wordsArray.push("possibility","trait","defect","glimpse","adolescence","disorder","illusion","sequence","bunch","shortcoming","sphere","diversity","outbreak","vacuum","drawback","aversion","bulk","criterion","chaos","fragment","perial","premise",/*"well-being",*/"counterpart","deed");
	wordsArray.push("outlet","assent","exposure","assumption","expression","column","greed","initiative","scope","preference","retirement","significance","solitude","stability","stake","overhaul","yield","cope","correspond","startle","ascend","compel","cast","float","sink");
	wordsArray.push("endanger","secure","marvel","abuse","discharge","halt","wrinkle","commence","disguise","resume","haunt","render","terminate","boost","prosper","coincide","shatter","deepen","enable","fasten","hasten","shorten","highlight","orient","renew");
	wordsArray.push("gigantic","intermediate","invaluable","perpetual","coarse","sheer","harsh","utmost","bent","explicit","superficial","ambiguous","savage","shabby","tiresome","grim","tedious","subsequent","audible","integral","inadequate","comparable","irrelevant","massive","invisible");
	
	wordsArray.push("athlete","pastime","recess","obstacle","insight","spectator","supervisor","aisle","reservation","brochure","lot","outcome","caution","applause","bullet","interval","riddle","aptitude","ovation","isolation","caricature","feast","intuition","prestige","tribute");
	wordsArray.push("layman","amenity","applicant","amateur","celebrity","stimulus","preoccupation","preview","procession","reasoning","install","anticipate","multiply","attain","leap","skip","violate","strive","register","conceal","overtake","confront","stir","prolong","shrug");
	wordsArray.push("accommodate","bump","thrust","lure","addict","steer","stumble","drag","accelerate","applaud","console","exert","bounce","clap","drift","justify","recruit","rejoice","slap","smash","strengthen","stride","tackle","tighten","trail");
	wordsArray.push("devise","hail","hug","sharpen","trim","secondhand","energetic","miserable","glorious","awkward","clumsy","masculine","vigorous","indispensable","divine","virtual","durable","brisk","mighty","versatile","proficient","preliminary","ardent","spontaneous","manifest");
	
	wordsArray.push("creed","meditation","synonym","autograph","pessimist","theme","paradox","craft","ritual","superstition","myth","tragedy","antonym","preface","masterpiece","reverence","prose","omen","metaphor","textile","verse","manuscript","ethics","ambition","inspiration");
	wordsArray.push("fake","portraint","patron","perfume","prophecy","representation","script","shrine","version","witch","devote","define","erect","fancy","tempt","conceive","incline","convey","exclude","utter","bless","revise","modify","entitle","illuminate");
	wordsArray.push("dedicate","glitter","worship","carve","preach","presume","curse","adore","presevere","enhance","muse","accord","characterize","erase","reproduce","complicate","contemplate","dictate","mold","recite","edit","interpret","uncover","unveil","visualize");
	wordsArray.push("vague","decent","vivid","wicked","authentic","magnificent","sacred","hollow","sophisticated","subtle","fragile","verbal","pious","elaborate","solemn","eminent","exquisite","vicious","dogmatic","ingenious","ethical","awesome","memorable","superb","subjective");
}